name: Build Ionic App and Deploy on FTP

on:
  push:
    branches:
      - ali # Trigger the workflow when changes are pushed to the 'ali' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2 

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Ionic
        run: npm install -g @ionic/cli

    
      - name: Install Dependencies
        run: npm install
      

     

      - name: Build Ionic App
        run: ionic build

       name: Copy Android
        run: ionic capacitor copy android

      - name: Build Android Dev APK
        run: ionic capacitor build android

      - name: Build Android Release APK
        run: ionic capacitor build android --release --prod
      
      - name: Build Android Project (APK)
        run: |
          cd android
          ./gradlew assembleRelease
        working-directory: android

      # - name: Build APK
      #   run: |
      #     mv platforms/android/app/build/outputs/apk/debug/app-debug.apk platforms/android/app/build/outputs/apk/debug/vacadmin.apk

      # - name: Upload APK
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: app-release
      #     path: android/app/build/outputs/apk/debug/vacadmin.apk
