name: Angular CI/CD (FTP Deployment)

on:
  push:
    branches: [demo, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g @ionic/cli # Install Ionic CLI globally
      - run: npm install
      - run: npm ci
      - run: ionic build --prod
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: www/
          retention-days: 1
  deploy-prod:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: www/
      - name: Deploy to production
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "198.54.114.164"
          username: "vacadmin@admin.vaccinationcentre.com"
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          port: 21
          protocol: ftps
          local-dir: www/
          server-dir: /
          state-name: "ftp-deploy-sync-state.json"
          timeout: 120000
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            web.config
