name: Angular CI/CD (FTP Deployment)

on:
  push:
    branches: [demo, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g @ionic/cli # Install Ionic CLI globally
      - run: npm install
      - run: npm ci
      - run: ionic build --prod
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: www/
          retention-days: 1

  deploy-demo:
    needs: build
    if: github.ref == 'refs/heads/demo'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: www/
      - name: Deploy to demo
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "${{ secrets.STAGING_FTP_SERVER }}"
          username: "${{ secrets.STAGING_FTP_USERNAME }}"
          password: "${{ secrets.STAGING_FTP_PASSWORD }}"
          local-dir: www/
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            web.config

  deploy-prod:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: www/
      - name: Deploy to production
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "198.54.114.164"
          username: "vacadmin@admin.vaccinationcentre.com"
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          local-dir: www/
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            web.config
